# Generated by Django 3.2.9 on 2021-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VITAZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
